# Generated by Django 2.2.24 on 2023-02-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_auto_20230217_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default=('medium', 'Medium'), max_length=10),
        ),
    ]
