# Generated by Django 2.2.24 on 2023-02-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_auto_20230217_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractor',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
    ]
